import argparse
from datetime import date, timedelta
from random import randint
import os
import urllib.request


def parse_command_line():
    """
    Parse the command line arguments and return the argparse object.
        
    There should be no positional arguments and 4 optional arguments.
    The help message generated by the parser should look like:
    usage: apod.py [-h] [-d month day year] [-s] [-k API_KEY] [-v]

    optional arguments:
      -h, --help            show this help message and exit
      -d month day year, --date month day year
                            formatted date (i.e. 03 28 1998)
      -s, --surprise        select a random date for a surprise image
      -k API_KEY, --api_key API_KEY
                            NASA developer key
      -v, --verbose         verbose mode


    HINT: for the --date optional argument, use a tuple: metavar = ("month", "day", "year")

    args:
        None
        
    returns:
        args: generated argparse object with all the parsed command line arguments      
    """
    
    #TODO: Your code goes here
    parser = argparse.ArgumentParser()
    parser.add_argument('-d', '--date',metavar=('month', 'day', 'year') , action='store', type=int, nargs=3, help='formatted date (i.e. 03 28 1998)')
    parser.add_argument('-s','--surprise', action='store_true', help='select a random date for a surprise image')
    parser.add_argument('-k', '--api_key', default='DEMO_KEY', help='NASA developer key')
    parser.add_argument('-v', '--verbose', action='store_true', help='verbose mode')
    args = parser.parse_args()
    return args

def main():
    # parse command line arguments
    args = parse_command_line()
    print(args.verbose)


main()
